name = "avian_pickup"
description = "Pick up and throw dynamic rigid bodies in Avian physics. Inspired by Half Life 2's gravity gun."
link = "https://github.com/janhohenheim/avian_pickup"
image = "avian_pickup.gif"
crate = "avian_pickup"
