name = "bevy_spicy_networking"
description = "Unifying server/client networking crate using tokio as asynchronous backend."
link = "https://github.com/CabbitStudios/bevy_spicy_networking"
bevy_versions = ["0.5"]
licenses = ["MIT"]
