name = "bevy_collider_gen"
description = "a library for generating 2D colliders for bevy apps from images"
link = "https://github.com/shnewto/bevy_collider_gen"
image = "bevy_collider_gen.png"
crate = "bevy_collider_gen"
