name = "seldom_pixel"
description = "Plugin for limited color palette pixel art games with animation, filters, typefaces, particles, etc."
link = "https://github.com/Seldom-SE/seldom_pixel"
image = "seldom_pixel.gif"
