name = "bevy_mod_ui_texture_atlas_image"
description = "Draw images from texture atlases with Bevy UI"
link = "https://github.com/ickshonpe/bevy_mod_ui_texture_atlas_image"
image = "bevy_mod_ui_texture_atlas_image..png"
