name = "bevy_vector_shapes"
description = "Draw configurable vector shapes. Supports retained and immediate modes for 2D, 3D and image targets."
link = "https://github.com/james-j-obrien/bevy_vector_shapes"
image = "bevy_vector_shapes.gif"