name = "Bevy Combat"
description = " A sci-fi battle simulation implemented in the bevy engine. "
link = "https://github.com/ElliotB256/bevy_combat"
image = "bevy_combat.gif"
bevy_versions = ["0.7"]
licenses = ["MIT"]
