name = "bevycheck"
description = "annotate invalid systems with `#[bevycheck::system]` to get nice error messages for what's wrong"
link = "https://github.com/jakobhellermann/bevycheck"
bevy_versions = ["0.7"]
licenses = ["MIT"]
