name = "blender_bevy_components_workflow"
description = "Crates & tools to add components, blueprints etc from gltf, to use Blender as an editor for Bevy"
link = "https://github.com/kaosat-dev/Blender_bevy_components_workflow"
image = "blender_bevy_components_workflow.png"