name = "Bevy Cheatbook"
description = "Unofficial reference book. Offers practical advice, teaches topics not covered by official docs."
link = "https://bevy-cheatbook.github.io"
bevy_versions = ["0.16"]
