name = "Bevy Noisemap Example"
description = "How to use Noisemap crate to generate random terrains"
link = "https://github.com/CiderSlime/bevy_noise_map"
image = "Bevy-Noisemap.png"
bevy_versions = ["0.12"]
