name = "Bevy 0.12 Beginner Video Tutorial Series"
description = "Master the essentials and kickstart your journey in game development with Bevy 0.12!"
link = "https://www.youtube.com/playlist?list=PL2wAo2qwCxGDp9fzBOTy_kpUTSwM1iWWd"
image = "Bevy_0.12_Beginner_Video_Tutorial_Series.png"
bevy_versions = ["0.12"]
