name = "Intro to Bevy Video Tutorials"
description = "Video Series making a simple Pokemon Style RPG"
link = "https://youtube.com/playlist?list=PLT_D88-MTFOPPl75g4WshL1Gx2bnGTUkz"
bevy_versions = ["0.8"]
